apiVersion: apps/v1
kind: Deployment
metadata:
  name: ods-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ods-backend
  template:
    metadata:
      labels:
        app: ods-backend
    spec:
      containers:
      - name: ods-backend
        image: ghcr.io/yourorg/ods-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: OLLAMA_URL
          value: "http://ollama:11434"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
